/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hwcmziqfleawqbobesgo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Y216aXFmbGVhd3Fib2Jlc2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODM0NTksImV4cCI6MjA3MTI1OTQ1OX0.MyCS4z4qQ0Dfl-NFGtdYI7Kf-Bm-vm4htt93ZwyHkwM"